### ISSUE TITLE
Issue about GLiNER NuNerZero span

### ISSUE THREAD

**Issue by Barianc** [Serega6678/NuNER#1]
Hello, thank you very much for your work. I wanted to ask if you could provide the training code for GLiNER NuNerZero span?  I hope to fully reproduce your work.

**Comment by Serega6678** [comment]
Hello @Barianc 
Unfortunately, all variations of NuNerZero were trained on the closed-source dataset (the one we didn't Open Source) thus it would not be possible to reproduce the training
Thank you for your question
